### ISSUE TITLE
Error with 

### ISSUE THREAD

**Issue by pierre-debruyne** [snelsi/next-hubspot#136]
**Describe the bug**
When i wrap my app in the provider i automatically get an error message
I'm on nextJS 12

export default function MyApp({ Component, pageProps }) {
  return (
    <AuthProvider>
      <HubspotProvider>
        <Component {...pageProps} />
      </HubspotProvider>
    </AuthProvider>
  );
}

Here is the error : 
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at HubspotProvider (file:///Users/pierre/Documents/GitHub/projetc/node_modules/next-hubspot/lib/HubspotProvider.js:17:28)
    at AuthProvider (webpack-internal:///./lib/auth.tsx:26:19)
    at MyApp (webpack-internal:///./pages/_app.tsx:25:18)
    at StyleRegistry (/Users/pierre/Documents/GitHub/projetc/node_modules/styled-jsx/dist/index/index.js:671:34)
    at AppContainer (/Users/pierre/Documents/GitHub/projetc/node_modules/next/dist/server/render.js:415:29)
    at AppContainerWithIsomorphicFiberStructure (/Users/pierre/Documents/GitHub/projetc/node_modules/next/dist/server/render.js:447:57)
    at div
    at Body (/Users/pierre/Documents/GitHub/projetc/node_modules/next/dist/server/render.js:715:21)

![Capture d’écran 2024-02-23 à 16 15 18](https://github.com/snelsi/next-hubspot/assets/25953085/57b237e3-81c0-4818-8f6d-eff97a7ebcf2)

If you have any idea or recommandation :)

**Comment by snelsi** [comment]
1) Context Providers should be added to the `_app` file and not to the `_document`
2) Support for Next.js version before 13 is not guaranteed

Context providers are used to manage global state or authentication state that needs to be accessed by various components across different pages. Placing them in the `_app.js` file ensures that they are initialized once and are available to all pages in your application.

Context providers are not typically added to the `_document.js` file because the `_document` is only concerned with the initial server render and the static HTML structure. Context providers, being components that manage state, are more relevant to the client-side rendering and need to be part of the React component tree, which is managed by the `_app` file for global application state.

**Comment by snelsi** [comment]
Relevant docs:
https://nextjs.org/docs/pages/building-your-application/routing/custom-app

**Comment by pierre-debruyne** [comment]
Thanks, the context provider is in _app.tsx, as you can see here : at MyApp (webpack-internal:///./pages/_app.tsx:25:18)
I guess there is something with next 12 compatibility :) I'll try to upgrade
